version: "3"
services:
  test:
    build: .
    volumes:
      - $PWD:/working
    container_name: atmacup8
    working_dir: /working
    ports:
      - 5000:5000
    environment:
      - PYTHONPATH=/working
    tty: true
